### ISSUE TITLE
On MySQL 5.6 with default utf8mb4 encoding, schema_migrations table fails to create

### ISSUE THREAD

**Issue by charlietran** [amacneil/dbmate#85] opened 2019-07-31 16:11 UTC
Running dbmate on my MySQL 5.6 server with the DEFAULT CHARSET utf8mb4 gave me this error:

```
Error: Error 1071: Specified key was too long; max key length is 767 bytes
```
It's because on MySql 5.6 InnoDB with utb8mb4 encoding, the max length limit for any key is 191 characters (utf8mb4 chars are 4 bytes each). Digging into the dbmate code, it looks like it's because the `schema_migrations`table is created as such:

```golang
// CreateMigrationsTable creates the schema_migrations table
func (drv MySQLDriver) CreateMigrationsTable(db *sql.DB) error {
	_, err := db.Exec("create table if not exists schema_migrations " +
		"(version varchar(255) primary key)")

	return err
}
```

255 chars * 4 bytes = 1020 bytes, which will go over the limit. This command will fail even if the `schema_migrations` table has already been manually created with a lower varchar limit. 

To fix this, we could possibly:

* Detect if the version is 5.6 and limit the varchar to 191
* Specify latin1 encoding for the schema_migrations table, which only takes 1 byte per character

What do you think? Thanks for making a great tool!

**Comment by andypalmer** [comment] 2019-08-16 07:30
You can also set the mysql table defaults to work with longer keys:
```
set @@global.innodb_default_row_format=DYNAMIC;
set @@global.innodb_file_format = BARRACUDA;
set @@global.innodb_large_prefix = 1;
```

**Comment by amacneil** [comment] 2019-09-23 17:17
I tried to reproduce this issue but can't unfortunately. I tried using MySQL 5.6, manually adding `DEFAULT CHARSET=utf8mb4` to the create table statement, adding `?charset=utf8mb4` to the connection string, and none of them caused an issue when creating this table or inserting a migration.

I think given that the date stamps we store are max 14 characters, I'm happy limiting this column (or explicitly specifying `utf8` or `latin1` when creating the table) if that helps, but I'm worried about publishing a fix for this if I can't reproduce it locally.

Are you able to create a docker image reproducing the issue?

**Comment by andypalmer** [comment] 2019-09-28 03:41
I put together a [quick demo](https://github.com/andypalmer/dbmate_key_length_problem).

**Comment by Enrico204** [comment] 2019-11-11 22:26
Same here - version `5.5.5-10.1.41-MariaDB-0+deb9u1`. Apparently the max size was increased in MySQL 5.6 onwards, so this behavior is not reproducible with newer engines.

**Comment by Enrico204** [comment] 2020-02-29 17:51
@amacneil you need to set the default server collation to `utf8mb4_general_ci` instead of using the connection one. Explanation:
* as the `schema_migrations` table is created without an explicit collation, it uses the database default
* the database is created without an explicit collation (using `dbmate create`), so it uses the default from the DB engine / DBMS
* the connection collation is used only for data transit in connection, not for table/database definition
* default collation for `CREATE DATABASE` is the default in the database (`collation_server`)

So, to reproduce it's sufficient to set `collation_server` to `utf8mb4_general_ci` (ignoring the collation of the connection) and have MySQL ~5.5 (or an equivalent MariaDB version).

I think that using `utf8` or `latin1` is sufficient, as the table only stores IDs in ASCII

**Comment by BigManWalter** [comment] 2020-04-09 15:07
I recently am getting the same issue on mariadb 10.1.44 Ubuntu 18.04.4 LTS.

**Closed** 2020-11-01 23:02 UTC
