### ISSUE TITLE
status command

### ISSUE THREAD

**Issue by MarkMurphy** [amacneil/dbmate#34] opened 2018-03-27 12:04 UTC
`dbmate status` would display the current migration status. 

It would also be nice to have an optional flag that would just output the number of pending migrations so that external systems can leverage that to warn when migrations are pending during an application boot process for example.

**Comment by amacneil** [comment] 2018-04-02 02:13
Thanks for the feature request, I believe it's a duplicate of https://github.com/amacneil/dbmate/issues/28

**Closed by amacneil** 2018-04-02 02:13 UTC
