### ISSUE TITLE
Inconsistencies with migrate and rollback.

### ISSUE THREAD

**Issue by matthewlenz** [amacneil/dbmate#30] opened 2018-01-24 19:45 UTC
Scenario.

2 developers working on different branches of code.

Developer 1 creates a new migration 20180124**192200**_featureA.sql

Developer 2 creates a new migration 20180124**203000**_featureB.sql

Developer 2's code is merged and put into production and dbmate is used to apply 20180124**203000**_FeatureB.sql.

Developer 1's code is merged and put into production and dbmate is used to apply 20180124**192200**_FeatureA.sql

I want to rollback FeatureA so I run:

$ dbmate rollback

but instead FeatureB is rolled back because it has a higher timestamp.

1. I want dbmate to apply any missing schema migrations.  I don't care about the timestamp and like the way 'migrate' works.
2. I want dbmate to rollback the most recently applied migration, not the migration with the highest timestamp.

How to fix this?

Add a timestamp to schema_migrations row and rollback the most recently applied migration that way rather than a descending sortin on the migration version.

**Comment by amacneil** [comment] 2018-01-25 00:11
Can you think of any good ways to solve this?

In my experience it's not a major issue, you just have to be aware that if you merge some code with a more recent migration timestamp, you need to rollback more than once if you want to change/reapply your migration.

At least if we implement https://github.com/amacneil/dbmate/issues/18 then it will be possibly to quickly rollback several migrations at once.

**Comment by matthewlenz** [comment] 2018-01-25 03:22
> Can you think of any good ways to solve this?'

Like I said, the only real option would be to place an additional column in the database that had the timestamp of when the specific migration was actually applied to the database.  Then you can look for the most recent migration by sorting on that timestamp column descending and limit the query to 1 row.  All old previously applied migrations could just get a timestamp based on their version number.  It does make an assumption about the old migrations but it's the same assumption that the code already makes so no harm imo.

**Comment by amacneil** [comment] 2018-01-29 03:21
Yeah, that would fix it.

I would really like to avoid adding additional columns to the `schema_migrations` table, so I don't think this issue is important enough to warrant a change there, and it's not clear that this would even be desired behavior (there might be an equal number of people who would expect `dbmate rollback` to revert migrations in the order they are defined on disk, regardless of which order they were ultimately applied in).

Thanks for reporting, but I think I will close this as expected behavior.

**Closed by amacneil** 2018-01-29 03:21 UTC

**Comment by wpalmer-psykhe** [comment] 2020-11-05 20:00
can this be reevaluated? I find the idea that "an equal number of people would want `down` to default to rolling back a migration other than the one most-recently applied `up`" to be more than a little hard to swallow - it certainly violates the "principle of least surprise".

Currently, the timestamp has the dual-purpose of being a unique identifier of the operation, *and* the "application order".

I definitely consider this to be critical, and I don't understand the hesitance to add additional columns to the `schema_migrations` table. In my "ideal world", the schema_migrations would include:

- unique identifier
- global application order
- application group (ie: `down` should default to acting as a reverse of `up`, and running `down` should default to running the reverse of all migrations within the group, with a non-default --step flag to get the current behaviour on `down`, or a "one at a time" behaviour on `up`)

Would a pull request implementing such features be accepted?

**Comment by amacneil** [comment] 2020-11-09 08:50
@wpalmer-psykhe would it help if you could `dbmate rollback [timestamp]` to roll back a specific timestamp?

I accept that it might be surprising for `dbmate rollback` to roll back a different migration than you just applied with `dbmate migrate`. However, in my experience it's uncommon (and often dangerous) to be rolling back migrations in production.

**Comment by wpalmer-psykhe** [comment] 2020-11-09 09:27
@amacneil the ability to roll back a specific timestamp would require manual record-keeping in order to know which timestamp to roll back. With that amount of manual process, there would be little reason to involve a migration tool at all.

I agree that it is uncommon and dangerous to roll back migrations in production, but this feels like a bit of a non sequitur - we're talking about the "rollback" function, which exists and so we clearly all accept that it is useful in some cases. In those cases, whatever the environment, applying rollbacks out-of-order is more dangerous than applying them in-order. If the assumption is that breaking the database via a rollback doesn't matter, because you can always rebuild the database from nothing, then that seems like more an argument against having a rollback feature at all.

The most-common scenario for running rollbacks is when testing a migration. The most-common method of testing a rollback (in my experience) is: 1) applying a migration  2) ensuring the new schema looks correct 3) immediately rolling back  4) ensuring the schema hasn't changed between pre-migration and post-rollback.

The most common scenario for running rollbacks in production is "undoing" a failed deploy.

In both such cases, "the most recent migration" is what should be rolled back. The current behaviour is effectively to roll back a *random* migration. One which is "somewhat likely" but has no guarantee to be the most-recent migration. In my view, being "likely, but not guaranteed" to be the expected behaviour is more dangerous than being always-literally-random, as it can cause a false sense of security/understanding.

As an extreme case: Last week I encountered a migration which was (legitimately) dated as being from 2014. Fortunately, this was in a different (non-go) project, which handles its migrations sanely, so rolling back "did the right thing", without my ever needing to be aware of the id. I only noticed when reviewing the diff before approving the PR.

I think the only way the current behaviour would make sense would be if the system error'd and refused to run at all were an out-of-order migration encountered.

**Comment by amacneil** [comment] 2020-11-09 09:50
I think this would be reasonable to add if you're interested in working on a PR. We should aim to keep it as minimal as possible (in line with dbmate's philosophy).

I can think of a few UX issues to work through, such as if several migrations were applied at once, whether `rollback` would roll back all of them or only the most recent (similar to https://github.com/amacneil/dbmate/issues/18).
