### ISSUE TITLE
dbmate does not support DOS/Windows file line endings

### ISSUE THREAD

**Issue by Quackster** [amacneil/dbmate#47] opened 2018-06-09 14:41 UTC
dbmate only supports files ending with '\n' instead of the usual Windows/DOS format which is '\r\n\'. 

Trying to perform a ``dbmate up`` command with migration files that have Windows/DOS line ending will result in an error, but it will work if the file is converted back to Unix line endings.

The error produced when trying to run on migration files with DOS file endings:
```
Applying: 20180605202455_query.sql
Error: Error 1065: Query was empty
```

**Comment by n0dai** [comment] 2018-08-07 22:56
I can confirm this bug too.

**Comment by amacneil** [comment] 2019-05-27 20:13
I'm unable to reproduce this (using windows line endings on linux or mac).

Can someone please post a minimal reproduction (preferably in a docker container) of this error?

**Comment by amacneil** [comment] 2019-09-18 21:28
Closing this issue because I cannot reproduce, if someone has clear steps (or preferably a git repo demonstrating the issue) please feel free to reopen.

**Closed by amacneil** 2019-09-18 21:28 UTC
