### ISSUE TITLE
Problems with transaction:false

### ISSUE THREAD

**Issue by trsh** [amacneil/dbmate#182] opened 2020-11-26 15:12 UTC
Hi! I am running dbmate migrations inside docker and for some reason the parameter `transaction:false` is completely ignored.

```
-- migrate:up transaction:false
CREATE INDEX CONCURRENTLY IF NOT EXISTS ....
```

and I still get  `Error: pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block`

Any advice where can I look, debug, configure?

**Comment by amacneil** [comment] 2020-11-26 19:30
Which version of dbmate are you using?

**Comment by trsh** [comment] 2020-11-26 19:32
@amacneil how can I check?

**Comment by trsh** [comment] 2020-11-26 20:08
Info from docker shell

```
app@742f084ae085:/app$ uname -a
Linux 742f084ae085 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux
```

**Comment by trsh** [comment] 2020-11-26 20:26
Did upgrade to `dbmate version 1.11.0` and same :(

**Comment by polymeris** [comment] 2021-04-05 00:14
Same here. Getting `Error: pq: CREATE MATERIALIZED VIEW ... WITH DATA cannot run inside a transaction block` on version 1.11.0 with:
```
-- migrate:up transaction:false
create materialized view 
...
```

**Comment by polymeris** [comment] 2021-04-05 00:21
Turns out I had more than one statement in the up migration, and apparently it can only be a single one if not in transaction.

**Comment by amacneil** [comment] 2021-04-10 17:22
That's definitely not intentional. I don't have time to investigate right now, but it should be possible to run multiple statements with `transaction:false`.

I'm fairly sure this used to work, so if someone has time to test out previous versions and figure out when this broke (`transaction:false` was added in v1.5.0) that would be helpful.

**Comment by AnatolyRugalev** [comment] 2021-06-21 15:09
The thing is that PostgreSQL wraps statements into internal transaction if they are executed outside of transaction. See (hacky) solution of that for go-migrate [here](https://github.com/golang-migrate/migrate/pull/495)

**Comment by atombender** [comment] 2022-01-05 20:58
This is still a problem with 1.12.1.

**Comment by Whoaa512** [comment] 2023-02-25 17:05
fwiw, I tried running this migration on v1.5 and it still fails with `Error: pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block`. However commenting out to only have 1 index created at a time worked, so seems like this has never worked for multiple statements, or at the very least multiple concurrent index creations.

```sql
-- migrate:up transaction:false
CREATE INDEX CONCURRENTLY invalidated_at_index ON jobs (invalidated_at);
CREATE INDEX CONCURRENTLY state_index ON jobs (state);
CREATE INDEX CONCURRENTLY status_index ON jobs (status);

-- migrate:down
DROP INDEX invalidated_at_index;
DROP INDEX state_index;
DROP INDEX status_index;
DROP INDEX metadata_expiring_rekick_submitted_index;
```

**Comment by vrajanap** [comment] 2023-04-19 00:40
This is likely the same issue as in https://github.com/amacneil/dbmate/issues/126.

**Comment by dossy** [comment] 2023-11-16 03:03
Duplicate of #126.

**Closed by dossy** 2023-11-16 03:03 UTC
Labels: bug, blocked
