### ISSUE TITLE
transaction:false not working on PostgreSQL

### ISSUE THREAD

**Issue by kashifsoofi** [amacneil/dbmate#285] opened 2022-03-24 09:45 UTC
Hi,
We are using dbmate for migrations, we are running into an issue where we want to run following
```
-- migrate:up transaction:false

CREATE INDEX CONCURRENTLY index_name ON table(new_id);
```

We are getting following error
`Error: pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block`

I didn't had to chance to run dbmate from source, has anyone else run into similar?

Thanks

**Comment by rohitpaulk** [comment] 2022-03-24 11:09
@kashifsoofi could you confirm what version of dbmate you're running?

**Comment by rohitpaulk** [comment] 2022-03-24 11:09
The `transaction:false` option was added in https://github.com/amacneil/dbmate/releases/tag/v1.5.0, I want to make sure that you're running a version that includes that change.

**Comment by kashifsoofi** [comment] 2022-03-24 11:11
I have tested with `dbmate version 1.11.0` and `dbmate version 1.14.0`, from code it looks like it should not create a transaction

**Comment by rohitpaulk** [comment] 2022-03-24 11:12
Got it, thanks! Will see if I can replicate.

**Comment by kashifsoofi** [comment] 2022-03-24 15:47
If I run a single CREATE INDEX CONCURRENTLY statement then there is no error

**Comment by kashifsoofi** [comment] 2022-03-24 15:56
Modifying test file in dbmate code

```
-- migrate:up
create table users (
  id integer,
  name varchar(255)
);
insert into users (id, name) values (1, 'alice');

CREATE INDEX CONCURRENTLY index_users_on_id ON users(id);

-- migrate:down
drop table users;
```

**Comment by kashifsoofi** [comment] 2022-03-24 16:28
I think the solution would be to somehow run each statement 1 by 1 incase there are multiple statements in a migration file.

**Comment by kashifsoofi** [comment] 2022-03-24 17:18
Something like this
```
func (m migrationOptions) MultiStatement() bool {
	if val, ok := m["multi-statement"]; ok {
		return val != "true"
	}

	return false
}
```
And then in db.go
```
...
			err = doTransaction(sqlDB, execMigration)
		} else if up.Options.MultiStatement() {
			var stmtSeparatorRegExp = regexp.MustCompile(`;`)
			stmts := stmtSeparatorRegExp.Split(up.Contents, -1)

			for i, stmt := range stmts {
				err = execMigrationStmt(sqlDB, stmt, i+1 == len(stmts))
				if err != nil {
					break
				}
			}
		} else {
			// run outside of transaction
...
```

**Comment by rohitpaulk** [comment] 2022-03-24 18:21
> https://github.com/amacneil/dbmate/issues/285#issuecomment-1077783065

@kashifsoofi if you use `transaction:false` in the script in that comment, does the error still occur? i.e. something like this: 

```
-- migrate:up transaction:false
create table users (
  id integer,
  name varchar(255)
);
insert into users (id, name) values (1, 'alice');

CREATE INDEX CONCURRENTLY index_users_on_id ON users(id);

-- migrate:down
drop table users;
```

**Comment by x-EricH-x** [comment] 2022-11-24 01:47
> @rohitpaulk Yes it does occur, however if I have file with only single step then there is no error
> 
> ```
> -- migrate:up transaction:false
> CREATE INDEX CONCURRENTLY index_users_on_id ON users(id);
> 
> -- migrate:down
> ```

Can confirm the same issue,
`-- migrate:up transaction:false` works when there is only one statement,
and fails when there are multiple.

**Comment by amacneil** [comment] 2022-12-19 07:33
Duplicate of #182

**Closed by amacneil** 2022-12-19 07:33 UTC
